name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # This workflow runs every day at 06:50 UTC
    - cron: '50 06 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all history for accurate commit information if needed for future steps
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Test Execution
      # Runs Maven clean and test goals
      run: mvn clean test

    - name: Upload logs artifact
      # Uploads the 'logs' directory as an artifact.
      # Ensure your Maven project is configured to output logs to a 'logs/' directory.
      uses: actions/upload-artifact@v4.6.2
      with:
        name: logs
        path: logs/
        # Optional: Set a retention period for the artifact (e.g., 5 days)
        # retention-days: 5
